Traceback (most recent call last):
  File "/taskscripts/inventory_optimization_task.py", line 203, in <module>
    args.optimization_definition, args.solver_name, args.solver_path, args.file_extension,args.directory_name,args.timestamp)
  File "/taskscripts/inventory_optimization_task.py", line 161, in OptimizeInventory
    result = solver.solve(instance)
  File "/opt/conda/lib/python3.5/site-packages/pyomo/opt/base/solvers.py", line 598, in solve
    default_variable_value=self._default_variable_value)
  File "/opt/conda/lib/python3.5/site-packages/pyomo/core/base/PyomoModel.py", line 225, in load_from
    "with bad status: %s" % str(results.solver.status))
ValueError: Cannot load a SolverResults object with bad status: error
